import { Property } from '@/types/property';
import { Category } from '@/types/category';

export const transformProperty = (data: any): Property => ({
    id: data.id,
    name: data.name,
    categoryId: data.categoryId,
    category: transformCategory(data.category),
    status: data.status,
    ownershipType: data.ownershipType,
    description: data.description,
    city: data.city,
    street: data.street,
    country: data.country,
    latitude: data.latitude || null,
    longitude: data.longitude || null,
    virtualTour: data.virtualTour || null,
    videoUrl: data.videoUrl || null,
    size: data.size,
    beds: data.beds,
    baths: data.baths,
    layout: data.layout || null,
    files: data.files || null,
    price: Number(data.price),
    discountedPrice: data.discountedPrice ? Number(data.discountedPrice) : null,
    buildingStoriesNumber: data.buildingStoriesNumber || null,
    buildingCondition: data.buildingCondition || null,
    apartmentCondition: data.apartmentCondition || null,
    aboveGroundFloors: data.aboveGroundFloors || null,
    reconstructionYearApartment: data.reconstructionYearApartment || null,
    reconstructionYearBuilding: data.reconstructionYearBuilding || null,
    totalAboveGroundFloors: data.totalAboveGroundFloors || null,
    totalUndergroundFloors: data.totalUndergroundFloors || null,
    floorArea: data.floorArea || null,
    builtUpArea: data.builtUpArea || null,
    gardenHouseArea: data.gardenHouseArea || null,
    terraceArea: data.terraceArea || null,
    totalLandArea: data.totalLandArea || null,
    gardenArea: data.gardenArea || null,
    garageArea: data.garageArea || null,
    balconyArea: data.balconyArea || null,
    pergolaArea: data.pergolaArea || null,
    basementArea: data.basementArea || null,
    workshopArea: data.workshopArea || null,
    totalObjectArea: data.totalObjectArea || null,
    usableArea: data.usableArea || null,
    landArea: data.landArea || null,
    objectType: data.objectType || null,
    objectLocationType: data.objectLocationType || null,
    houseEquipment: data.houseEquipment || null,
    accessRoad: data.accessRoad || null,
    objectCondition: data.objectCondition || null,
    reservationPrice: data.reservationPrice || null,
    equipmentDescription: data.equipmentDescription || null,
    additionalSources: data.additionalSources || null,
    buildingPermit: data.buildingPermit || null,
    buildability: data.buildability || null,
    utilitiesOnLand: data.utilitiesOnLand || null,
    utilitiesOnAdjacentRoad: data.utilitiesOnAdjacentRoad || null,
    payments: data.payments || null,
    brokerId: data.brokerId || null,
    secondaryAgent: data.secondaryAgent || null,
    createdAt: data.createdAt,
    updatedAt: data.updatedAt,
    images: data.images || [],
    floorplans: data.floorplans || [],
    reviews: data.reviews || [],
    translations: data.translations || {},
    priceHidden: data.priceHidden ?? false,
});

export const transformCategory = (data: any): Category => ({
    id: data.id,
    name: data.name,
    slug: data.slug,
    image: data.image,
    createdAt: data.createdAt,
    updatedAt: data.updatedAt
}); 